# Config del servidor
server.port=8080

# Config Hibernate
spring.jpa.properties.hibernate.entity_manager_factory_interface=jakarta.persistence.EntityManagerFactory
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect