#Import Common config
spring.config.import=application-common.properties

#Url front
url.client=http://localhost:4200

# Config Hibernate en desarrollo
spring.jpa.hibernate.ddl-auto=create-drop

# Config de logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#BD Config cambiar ip
spring.application.name=healthturing_server
spring.datasource.url=jdbc:mysql://localhost:3306/healthTuringDB
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#CORS allowed
cors.allowedOrigins=http://localhost:4200

# Config de JWT
jwt.secret=${JWT_SECRET}


