#Import Common config
spring.config.import=application-common.properties

spring.jpa.hibernate.ddl-auto=create-drop

#Url front
url.client=http://localhost:4200

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#BD Config cambiar ip
spring.datasource.url=jdbc:mysql://localhost:3306/healthTuringDB
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#CORS allowed
cors.allowedOrigins=http://localhost:4200

jwt.secret=${JWT_SECRET}
# Config Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Configuración de logs (más detallada en desarrollo)
# logging.level.org.hibernate.SQL=DEBUG
# logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
