name: Build and Deploy Fullstack

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        frontend_host: [3.95.121.200]
        backend_host: [184.73.19.56]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Build Angular
        run: |
          cd frontend/healthTuring-client
          npm install
          npm run build -- --configuration production

      - name: Show Angular dist contents
        run: ls -lh frontend/healthTuring-client/dist/health-turing-client/browser

      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot
        run: |
          cd backend/healthturing-server
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      - name: Show JAR generado
        run: ls -lh backend/healthturing-server/target/

      - name: Upload Angular build to EC2 (frontend)
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ matrix.frontend_host }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "frontend/healthTuring-client/dist/health-turing-client/browser/*"
          target: "/home/ubuntu/frontend-dist"

      - name: Verificar archivos frontend en EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ matrix.frontend_host }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            ls -lh /home/ubuntu/frontend-dist

      - name: Upload Spring Boot JAR to EC2 (backend)
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ matrix.backend_host }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "backend/healthturing-server/target/healthturing-server-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/app.jar"

      - name: Verificar app.jar en EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ matrix.backend_host }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            ls -lh /home/ubuntu/app.jar
