name: Test Frontend Deploy

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.2.0'

      - name: Build Angular
        run: |
          cd frontend/healthTuring-client
          npm install
          npm run build -- --configuration production

      - name: Upload Angular build to EC2 (TEST)
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "frontend/healthTuring-client/dist/health-turing-client/browser/*"
          target: "/home/ubuntu/frontend-dist"

      - name: Check frontend files
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            ls -lh /home/ubuntu/frontend-dist || echo "⚠️ No frontend files deployed"
